config/routes.rb
Rails.application.routes.draw do
  get 'schedules/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :schedules do
    get :search, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
    validates :title, presence: true
    validates :start_day, presence: true
    validates :end_day, presence: true
    validate :start_over_end
    def start_over_end
        if start_day >=end_day
            errors.add(:end_day, "を開始日以降にしてください")
        end
    end
    
    def self.sort(selection)
        case selection
            when "update"
                return all.order(updated_at: :DESC)
            when "start"
                return all.order(start_day: :ASC)
            when "end"
                return all.order(end_day: :ASC)
            end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
    def index
        @schedules = Schedule.all
        @record_count = "スケジュール合計：#{Schedule.count}"
    end
    
    def new
        @schedule = Schedule.new
    end
    
    def create
        @schedule = Schedule.new(params.require(:schedule).permit(:title, :start_day, :end_day, :all_day, :memo))
        if @schedule.save
            flash[:notice] = "スケジュールを登録しました"
            redirect_to :schedules
        else
            flash[:notice] = "登録できませんでした"
            render "new"
        end
    end
    
    def show
        
        @schedule = Schedule.find(params[:id])
    end
    
    def edit
        @schedule = Schedule.find(params[:id])
    end
    
    def update
        @schedule = Schedule.find(params[:id])
        if @schedule.update(params.require(:schedule).permit(:title, :start_day, :end_day, :all_day, :memo))
            flash[:notice] = "ID#{@schedule.id}のスケジュールの更新をしました"
            redirect_to :schedules
        else
            flash[:notice] = "編集できませんでした"
            render "edit"
        end
    end
    
    def destroy
        @schedule = Schedule.find(params[:id])
        @schedule.destroy
        flash[:notice] = "スケジュールを削除しました"
        redirect_to :schedules
    end
    
    def search
        selection = params[:schedule][:keyword]
        
        @schedules = Schedule.sort(selection)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>Ruby on Rails スケジュール管理アプリ</h1>
    </header>
    <div class="container">
      <%= yield %>
    </div>
    <footer>
      <h1>
        現在の日時：<%= Time.now.to_s(:datetime_jp) %><%= render "shared/partial" %>
      </h1>
    </footer>
  </body>
</html>

app/views/schedules/edit.html.erb
<h2>スケジュール編集</h2>
<% if flash.notice %>
  <p class="notice"><%= flash.notice %></p>
<% end %>
<%= render "shared/error" , obj: @schedule %>

<%= form_for @schedule do |f| %>
<table>

  <tr>
    <th><%= f.label :title, "タイトル" %></th>
    <td><%= f.text_field :title %></td>
  </tr>
  <tr>
    <th><%= f.label :start_day, "開始日" %></th>
    <td><%= f.datetime_field :start_day %></td>
  </tr>
  <tr>
    <th><%= f.label :end_day, "終了日" %></th>
    <td><%= f.datetime_field :end_day %></td>
  </tr>
  <tr>
    <th><%= f.label :all_day, "終日" %></th>
    <td>
      <%= f.hidden_field :all_day, value: 0 %>
      <%= f.check_box :all_day %>終日の場合はチェックを入れます</td>

  </tr>
  <tr>
    <th><%= f.label :memo, "スケジュールメモ" %></th>
    <td><%= f.text_area :memo, class: "textarea" %></td>
  </tr>
</table>
<div class="">
  <ul>
    <li><%= f.submit "編集を完了する" %></li>
    <li><%= link_to "スケジュール一覧に戻る", :schedules %><li>
  </ul>
</div>
<% end %>

app/views/schedules/index.html.erb
<h2>スケジュール一覧</h2>
<% if flash.notice %>
  <p class="notice"><%= flash.notice %></p>
<% end %>
<%= form_with model: @schedules, url: search_schedules_path, method: :get, local: true do |f| %>
  <%= f.select :keyword, [['更新日時' , 'update'],['開始日' , 'start'],['終了日', 'end']] %>
  <%= f.submit "ソート" %>
<% end %>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>タイトル</th>
      <th>開始日</th>
      <th>終了日</th>
      <th>終日</th>
      <th>更新日時</th>
      <th>確認</th>
      <th>編集</th>
      <th>削除</th>
    </tr>
  </thead>
  <tbody>
    <% @schedules.each do |sche| %>
    <tr>
      <td><%= sche.id %></td>
      <td><%= sche.title %></td>
      <td><%= sche.start_day.strftime("%Y年 %m月%d日 %H:%M") %></td>
      <td><%= sche.end_day.strftime("%Y年 %m月%d日 %H:%M") %></td>
      <% if sche.all_day == true %>
        <% all_day = "◯" %>
      <% else %>
        <% all_day = "" %>
      <% end %>
      <td><%= all_day %></td>
      <td><%= sche.updated_at.to_s(:datetime_jp) %></td>
      <td><%= link_to "確認" , sche %></td>
      <td><%= link_to "編集" , [:edit, sche]%></td>
      <td><%= link_to "削除" , sche, method: :delete, data: { confirm: "本当に削除しますか" } %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<div class="">
  <ul>
    <li><%= link_to "スケジュール新規登録", :new_schedule %></li>
  </ul>
</div>

app/views/schedules/new.html.erb
<h2>スケジュール作成</h2>
<% if flash.notice %>
  <p class="notice"><%= flash.notice %></p>
<% end %>
<%= render "shared/error" , obj: @schedule %>

<%= form_for @schedule do |f| %>
<table>

  <tr>
    <th><%= f.label :title, "タイトル" %></th>
    <td><%= f.text_field :title %></td>
  </tr>
  <tr>
    <th><%= f.label :start_day, "開始日" %></th>
    <td><%= f.datetime_field :start_day %></td>
  </tr>
  <tr>
    <th><%= f.label :end_day, "終了日" %></th>
    <td><%= f.datetime_field :end_day %></td>
  </tr>
  <tr>
    <th><%= f.label :all_day, "終日" %></th>
    <td>
      <%= f.hidden_field :all_day, value: 0 %>
      <%= f.check_box :all_day %>終日の場合はチェックを入れます</td>

  </tr>
  <tr>
    <th><%= f.label :memo, "スケジュールメモ" %></th>
    <td><%= f.text_area :memo, class: "textarea" %></td>
  </tr>
</table>
<div class="">
  <ul>
    <li><%= f.submit "スケジュールを登録する" %></li>
    <li><%= link_to "スケジュール一覧に戻る", :schedules %><li>
  </ul>
</div>
<% end %>

app/views/schedules/search.html.erb
<h2>スケジュール一覧</h2>
<% if flash.notice %>
  <p class="notice"><%= flash.notice %></p>
<% end %>
<%= form_with model: @schedules, url: search_schedules_path, method: :get, local: true do |f| %>
  <%= f.select :keyword, [['更新日時' , 'update'],['開始日' , 'start'],['終了日', 'end']] %>
  <%= f.submit "ソート" %>
<% end %>
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>タイトル</th>
      <th>開始日</th>
      <th>終了日</th>
      <th>終日</th>
      <th>更新日時</th>
      <th>確認</th>
      <th>編集</th>
      <th>削除</th>
    </tr>
  </thead>
  <tbody>
    <% @schedules.each do |sche| %>
    <tr>
      <td><%= sche.id %></td>
      <td><%= sche.title %></td>
      <td><%= sche.start_day.strftime("%Y年 %m月%d日 %H:%M") %></td>
      <td><%= sche.end_day.strftime("%Y年 %m月%d日 %H:%M") %></td>
      <% if sche.all_day == true %>
        <% all_day = "◯" %>
      <% else %>
        <% all_day = "" %>
      <% end %>
      <td><%= all_day %></td>
      <td><%= sche.updated_at.to_s(:datetime_jp) %></td>
      <td><%= link_to "確認" , sche %></td>
      <td><%= link_to "編集" , [:edit, sche]%></td>
      <td><%= link_to "削除" , sche, method: :delete, data: { confirm: "本当に削除しますか" } %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<div class="">
  <ul>
    <li><%= link_to "スケジュール新規登録", :new_schedule %></li>
  </ul>
</div>

app/views/schedules/show.html.erb
<h2>スケジュール詳細</h2>
<table>
  <tr>
    <th>タイトル</th>
    <td><%= @schedule.title %></td>
  </tr>
  <tr>
    <th>開始日</th>
    <td><%= @schedule.start_day.strftime("%Y年 %m月%d日 %H:%M") %></td>
  </tr>
  <tr>
    <th>終了日</th>
    <td><%= @schedule.end_day.strftime("%Y年 %m月%d日 %H:%M") %></td>
  </tr>
  <tr>
    <th>終日</th>
    <% if @schedule.all_day == true %>
      <% all_day = "◯" %>
    <% else %>
      <% all_day = "" %>
    <% end %>
    <td><%= all_day %></td>
  </tr>
  <tr>
    <th>スケジュールメモ</th>
    <td><%= @schedule.memo %></td>
  </tr>
</table>
<div class="">
  <ul>
    <li><%= link_to "スケジュール一覧に戻る", :schedules %></li>
    <li><%= link_to "スケジュールを編集する", [:edit, @schedule] %></li>
    <li><%= link_to "スケジュール削除", schedule_path, method: :delete, data: {confirm: "本当に削除しますか？"} %></li>
  </ul>
</div>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
  <% obj.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>

app/views/shared/_partial.html.erb
<span>
<%= @record_count %>
</span>